import type { Evidence, Finding, ScanReport } from "./types.js";

function esc(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

function evidenceCell(evidence: Evidence[]): string {
  if (evidence.length === 0) return "—";
  return evidence.slice(0, 5).map((ev) => `${ev.file}:${ev.line}`).join(", ");
}

function findingRow(finding: Finding): string {
  return `| ${esc(finding.variable)} | ${finding.kind} | ${finding.severity} | ${esc(finding.message)} | ${esc(evidenceCell(finding.evidence))} |`;
}

export function renderMarkdown(report: ScanReport): string {
  const lines: string[] = [];
  lines.push("# EnvDiffKit Report");
  lines.push("");
  lines.push(`Generated by envdiffkit ${report.version}. Deterministic timestamp: ${report.generatedAt}.`);
  lines.push("");
  lines.push("## Safety");
  lines.push("");
  lines.push(`- Values redacted: ${report.safety.valuesRedacted ? "yes" : "no"}`);
  lines.push(`- Real env files included: ${report.safety.realEnvIncluded ? "yes" : "no"}`);
  lines.push(`- ${report.safety.note}`);
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(`- Used variables: ${report.summary.used}`);
  lines.push(`- Documented variables: ${report.summary.documented}`);
  lines.push(`- Missing from example: ${report.summary.missing}`);
  lines.push(`- Stale in example: ${report.summary.stale}`);
  lines.push(`- Suspicious secret-like names: ${report.summary.suspicious}`);
  lines.push(`- Ignored low-signal references: ${report.summary.ignored}`);
  lines.push("");
  lines.push("## Findings");
  lines.push("");
  if (report.findings.length === 0) {
    lines.push("No findings. Your env surface looks tidy. 🌱");
  } else {
    lines.push("| Variable | Kind | Severity | Message | Evidence |");
    lines.push("| --- | --- | --- | --- | --- |");
    for (const finding of report.findings) lines.push(findingRow(finding));
  }
  lines.push("");
  lines.push("## Variables");
  lines.push("");
  lines.push("| Variable | Used | Documented | Suspicious | Evidence |");
  lines.push("| --- | --- | --- | --- | --- |");
  for (const variable of report.variables) {
    lines.push(`| ${esc(variable.name)} | ${variable.used ? "yes" : "no"} | ${variable.documented ? "yes" : "no"} | ${variable.suspicious ? "yes" : "no"} | ${esc(evidenceCell(variable.evidence))} |`);
  }
  lines.push("");
  return `${lines.join("\n")}\n`;
}
